In [238]:
import pandas as pd
import os
import importlib

import modify_cv
import modify_cv2
import load

modify_cv = importlib.reload(modify_cv)
modify_cv2 = importlib.reload(modify_cv2)
load = importlib.reload(load)

ORIGINAL_CVS_FOLDER = "original_cvs"
MODIFIED_CVS_FOLDER = "modified_cvs"

# Load the CVs dataset of UI/UX Designers and Project Managers from `load.ipynb`

In [40]:
uiux_pm_520_df = pd.read_csv(os.path.join(ORIGINAL_CVS_FOLDER, "original_cvs.csv"), index_col=0)

# Load all data and keys

In [41]:
api_keys = load.load_api_keys()

modification_prompt_names, modification_prompts = load.get_modification_prompts()
modification_prompts_dict = dict(zip(modification_prompt_names, modification_prompts))
modification_prompt_from_paper_name = "from_paper"
modification_prompt_from_paper = modification_prompts_dict[modification_prompt_from_paper_name]

job_descriptions_pm_names, job_descriptions_pm = load.get_pm_job_descriptions()
job_descriptions_pm_dict = dict(zip(job_descriptions_pm_names, job_descriptions_pm))
job_description_doordash_name = "doordash_pm"
job_description_doordash = job_descriptions_pm_dict[job_description_doordash_name]

job_descriptions_uiux_names, job_descriptions_uiux = load.get_uiux_job_descriptions()
job_descriptions_uiux_dict = dict(zip(job_descriptions_uiux_names, job_descriptions_uiux))
job_descriptions_google_ux_name = "google_ux"
job_descriptions_google_ux = job_descriptions_uiux_dict[job_descriptions_google_ux_name]

In [46]:
def run_experiment(
    client, df: pd.DataFrame = uiux_pm_520_df, save_to: str | None = None
) -> pd.DataFrame:
    if len(df.columns) == 1:
        df_just_cvs = df[[df.columns[0]]].copy()
    elif "CV" in df.columns:
        df_just_cvs = df[["CV"]].copy()
    else:
        raise ValueError("DataFrame must have either one column or a column named 'CV'")

    df_modified_cvs = client.generate_group_of_cv_s(df_just_cvs)
    if save_to is not None:
        df_modified_cvs.to_csv(save_to)
    return df_modified_cvs

# Modifying CVs with Anthropic's Haiku 4.5

In [47]:
haiku_4_5_modification_client_doordash_original_prompt = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-haiku-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

haiku_4_5_modification_client_google_ux_original_prompt = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-haiku-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [8]:
run_experiment(
    client=haiku_4_5_modification_client_google_ux_original_prompt,
    save_to="uiux_pm_520_haiku_modified_cvs_google_ux.csv",
)

run_experiment(
    client=haiku_4_5_modification_client_doordash_original_prompt,
    save_to="uiux_pm_520_haiku_modified_cvs_doordash.csv",
)

Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...

      Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5
6018   **Web & UX/UI Designer**\n\n**Professional Sum...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\n- Over ...
6026   # Design Professional\n\n**PROFESSIONAL SUMMAR...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL PROFILE\n\...
15743  # Cloud Architect\n\n**Core Expertise**\nCloud...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

#### And a second modification with the same prompts and model

In [48]:
run_experiment(
    client=haiku_4_5_modification_client_doordash_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "haiku_doordash_pm.csv"), index_col=0),
    save_to="pm_520_haiku_twice_modified_cvs_doordash.csv",
)

Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...

      Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5
6018   **Web & UX/UI Designer**\n\n**Professional Sum...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\n- Over ...
6026   # Design Professional\n\n**PROFESSIONAL SUMMAR...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **DEPOSITPHOTOS | Content Researcher**\n\nCrea...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL PROFILE\n\...
15743  # Cloud Architect\n\n**Core Expertise**\nCloud...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

In [49]:
run_experiment(
    client=haiku_4_5_modification_client_google_ux_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "haiku_google_ux.csv"), index_col=0),
    save_to="pm_520_haiku_twice_modified_cvs_google_ux.csv",
)

Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...

      Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5
6018   **WEB AND UX/UI DESIGNER**\n\n**PROFESSIONAL E...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\nOver 50...
6026   # PROFESSIONAL SUMMARY\n\nDesign Professional ...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\nC...
15743  # Cloud Architect\n\n**Professional Summary**\...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

#### And a third modification with Haiku 4.5 Preview

In [252]:
run_experiment(
    client=haiku_4_5_modification_client_doordash_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "twice_haiku_doordash_pm.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "thrice_haiku_doordash_pm.csv")
)

run_experiment(
    client=haiku_4_5_modification_client_google_ux_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "twice_haiku_google_ux.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "thrice_haiku_google_ux.csv")
)

Batch msgbatch_016oibM6tduBBMnrdZmUztdS is still processing...
Batch msgbatch_016oibM6tduBBMnrdZmUztdS is still processing...
Batch msgbatch_016oibM6tduBBMnrdZmUztdS is still processing...
Batch msgbatch_016oibM6tduBBMnrdZmUztdS is still processing...
Batch msgbatch_01TotR9q923BUGzeyP2e17og is still processing...
Batch msgbatch_01TotR9q923BUGzeyP2e17og is still processing...
Batch msgbatch_01TotR9q923BUGzeyP2e17og is still processing...
Batch msgbatch_01TotR9q923BUGzeyP2e17og is still processing...
Batch msgbatch_01TotR9q923BUGzeyP2e17og is still processing...
Batch msgbatch_01TotR9q923BUGzeyP2e17og is still processing...

      Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5
6018   **WEB AND UX/UI DESIGNER**\n\n**PROFESSIONAL E...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\nOver 50...
6026   # PROFESSIONAL SUMMARY\n\nDesign Professional ...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\nC...
15743  # Cloud Architect\n\n**Professional Summary**\...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

#### Fourth modification with Haiku 4.5

In [257]:
run_experiment(
    client=haiku_4_5_modification_client_doordash_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "thrice_haiku_doordash_pm.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "fourth_haiku_doordash_pm.csv")
)

run_experiment(
    client=haiku_4_5_modification_client_google_ux_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "thrice_haiku_google_ux.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "fourth_haiku_google_ux.csv")
)

Batch msgbatch_014r9zDEyPHLyoR51otLHjxL is still processing...
Batch msgbatch_014r9zDEyPHLyoR51otLHjxL is still processing...
Batch msgbatch_014r9zDEyPHLyoR51otLHjxL is still processing...
Batch msgbatch_014r9zDEyPHLyoR51otLHjxL is still processing...
Batch msgbatch_01Ab2bFtBfUgZBhCFZRb17Jq is still processing...
Batch msgbatch_01Ab2bFtBfUgZBhCFZRb17Jq is still processing...
Batch msgbatch_01Ab2bFtBfUgZBhCFZRb17Jq is still processing...
Batch msgbatch_01Ab2bFtBfUgZBhCFZRb17Jq is still processing...

      Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5
6018   **WEB AND UX/UI DESIGNER**\n\n**PROFESSIONAL E...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\nOver 50...
6026   # PROFESSIONAL SUMMARY\n\nDesign Professional ...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\nC...
15743  # Cloud Architect\n\n**Professional Summary**\...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

# Modify with Anthropic's Opus 4.5

In [50]:
opus_4_5_modification_client_doordash = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-opus-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

opus_4_5_modification_client_google_ux = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-opus-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [14]:
run_experiment(
    opus_4_5_modification_client_doordash,
    uiux_pm_520_df,
    save_to="uiux_pm_520_opus_modified_cvs_doordash.csv",
)

run_experiment(
    opus_4_5_modification_client_google_ux,
    uiux_pm_520_df,
    save_to="uiux_pm_520_opus_modified_cvs_google_ux.csv",
)

Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...

      Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5
6018   # WEB & UX/UI DESIGNER\n\n## Professional Summ...
6021   # PROFESSIONAL EXPERIENCE\n\n**Head of Design ...
6026   **DESIGN PROFESSIONAL**\n\n---\n\nDesign is my...
9479   # GRAPHIC DESIGNER | LEAD GRAPHIC DESIGNER\n\n...
16980  PROFESSIONAL EXPERIENCE\n\nDepositphotos | Con...
...                                                  ...
15679  # DARIA MALININA\n\n**Languages:** Chinese, It...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  **[Name]**\n[Contact Information]\n\n---\n\n**...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

#### And a second modification with the same prompts and model

In [ ]:
run_experiment(
    client=opus_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "opus_doordash_pm.csv"), index_col=0),
    save_to="pm_520_opus_twice_modified_cvs_doordash.csv",
)

Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5_Modelclaude-opus-4-5
6018   # PROFESSIONAL RESUME\n\n## Web Designer & UX/...
6021   # [NAME]\n## Head of Design Department\n\n---\...
6026   # PROFESSIONAL SUMMARY\n\nSenior Product Desig...
9479   # GRAPHIC DESIGNER | UI/UX DESIGNER\n\n## PROF...
16980  **DEPOSITPHOTOS**\n**Content Researcher**\n\n-...
...                                                  ...
15679  # DARIA MALININA\n\n---\n\n## Professional Sum...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # SENIOR MARKETING & BRAND STRATEGY LEADER\n\n...
16039  **Professional Experience**\n\n**Team Lead - E...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

In [52]:
run_experiment(
    client=opus_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "opus_google_ux.csv"), index_col=0),
    save_to="pm_520_opus_twice_modified_cvs_google_ux.csv",
)

Batch msgbatch_01LRKdN2Kj5jd3NUiNm4KJhU is still processing...
Batch msgbatch_01LRKdN2Kj5jd3NUiNm4KJhU is still processing...
Batch msgbatch_01LRKdN2Kj5jd3NUiNm4KJhU is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5_Modelclaude-opus-4-5
6018   # WEB & UX/UI DESIGNER\n\n## Professional Summ...
6021   # PROFESSIONAL EXPERIENCE\n\n**Head of Design ...
6026   **DESIGN PROFESSIONAL**\n\n---\n\n**SUMMARY**\...
9479   # GRAPHIC DESIGNER | LEAD GRAPHIC DESIGNER\n\n...
16980  PROFESSIONAL EXPERIENCE\n\n**Depositphotos | C...
...                                                  ...
15679  # DARIA MALININA\n\n**Languages:** Chinese, It...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # PROFESSIONAL SUMMARY\n\nVersatile marketing ...
16039  **[Name]**\n[Contact Information]\n\n---\n\n**...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

#### And a third modification with Opus 4.5

In [ ]:
run_experiment(
    client=opus_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "twice_opus_doordash_pm.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "thrice_opus_doordash_pm.csv")
)

Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...
Batch msgbatch_01XnCetwDwR32fXS8NJjx53N is still processing...

FileNotFoundError: [Errno 2] No such file or directory: 'modified_cvs/twice_opus_google_ux_pm.csv'

In [250]:
run_experiment(
    client=opus_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "twice_opus_google_ux.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "thrice_opus_google_ux.csv")
)

Batch msgbatch_01GPuhRt8LPpziQ5G6j9Y87K is still processing...
Batch msgbatch_01GPuhRt8LPpziQ5G6j9Y87K is still processing...
Batch msgbatch_01GPuhRt8LPpziQ5G6j9Y87K is still processing...
Batch msgbatch_01GPuhRt8LPpziQ5G6j9Y87K is still processing...
Batch msgbatch_01GPuhRt8LPpziQ5G6j9Y87K is still processing...
Batch msgbatch_01GPuhRt8LPpziQ5G6j9Y87K is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5_Modelclaude-opus-4-5_Modelclaude-opus-4-5
6018   # WEB & UX/UI DESIGNER\n\n## Professional Summ...
6021   # PROFESSIONAL EXPERIENCE\n\n**Head of Design ...
6026   **DESIGN PROFESSIONAL**\n\n---\n\n**SUMMARY**\...
9479   # GRAPHIC DESIGNER | LEAD GRAPHIC DESIGNER\n\n...
16980  **PROFESSIONAL EXPERIENCE**\n\n**Depositphotos...
...                                                  ...
15679  # DARIA MALININA\n\n---\n\n## PROFESSIONAL SUM...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # PROFESSIONAL SUMMARY\n\nVersatile marketing ...
16039  **[Name]**\n[Contact Information]\n\n---\n\n**...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

#### And a fourth time with Opus 4.5

In [ ]:
run_experiment(
    client=opus_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "thrice_opus_google_ux.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "fourth_opus_google_ux.csv")
)

Batch msgbatch_01Uc3aqye62HequYKeKszdXo is still processing...
Batch msgbatch_01Uc3aqye62HequYKeKszdXo is still processing...
Batch msgbatch_01Uc3aqye62HequYKeKszdXo is still processing...
Batch msgbatch_01Uc3aqye62HequYKeKszdXo is still processing...
Batch msgbatch_01Uc3aqye62HequYKeKszdXo is still processing...

BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.'}, 'request_id': 'req_011CXLSy26diFrEoEojr8YBU'}

In [256]:
run_experiment(
    client=opus_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "thrice_opus_doordash_pm.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "fourth_opus_doordash_pm.csv")
)

Batch msgbatch_01U2jtMZZsXGyPe5RAPzu776 is still processing...
Batch msgbatch_01U2jtMZZsXGyPe5RAPzu776 is still processing...
Batch msgbatch_01U2jtMZZsXGyPe5RAPzu776 is still processing...
Batch msgbatch_01U2jtMZZsXGyPe5RAPzu776 is still processing...
Batch msgbatch_01U2jtMZZsXGyPe5RAPzu776 is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5_Modelclaude-opus-4-5_Modelclaude-opus-4-5_Modelclaude-opus-4-5
6018   # PROFESSIONAL RESUME\n\n## Web Designer & UX/...
6021   # [NAME]\n## Head of Design Department\n\n---\...
6026   # PROFESSIONAL SUMMARY\n\nSenior Product Desig...
9479   # GRAPHIC DESIGNER | UI/UX DESIGNER\n\n## PROF...
16980  **PROFESSIONAL EXPERIENCE**\n\n**DEPOSITPHOTOS...
...                                                  ...
15679  # DARIA MALININA\n\n---\n\n## Professional Sum...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # SENIOR MARKETING & BRAND STRATEGY LEADER\n\n...
16039  **Professional Experience**\n\n**Team Lead — E...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

# And with Anthropic's Sonnet 4.5

In [53]:
sonnet_4_5_modification_client_doordash = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-sonnet-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

sonnet_4_5_modification_client_google_ux = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-sonnet-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [10]:
run_experiment(
    sonnet_4_5_modification_client_doordash,
    uiux_pm_520_df,
    save_to="sonnet_4_5_doordash_original_prompt_modified_cvs.csv",
)

run_experiment(
    sonnet_4_5_modification_client_google_ux,
    uiux_pm_520_df,
    save_to="sonnet_4_5_google_ux_original_prompt_modified_cvs.csv",
)

Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...

      Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Professional Expe...
6021   Over 50 Websites\nMore than 30 Logotypes\n4 Mo...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **Content Researcher**  \nDepositphotos\n\n• R...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\n\...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\n**Team Lead - Email...
16064  **PROFESSIONAL SUMMARY**\n\nResults-driven mar...

[520 rows x 1 columns]

In [54]:
run_experiment(
    client=sonnet_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "sonnet_doordash_pm.csv"), index_col=0),
    save_to="pm_520_sonnet_twice_modified_cvs_doordash.csv",
)

Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...

      Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Professional Expe...
6021   PORTFOLIO HIGHLIGHTS\nOver 50 Websites\nMore t...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  # PROFESSIONAL EXPERIENCE\n\n**Content Researc...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\n\...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\n**Team Lead - Email...
16064  # PROFESSIONAL SUMMARY\n\nResults-driven marke...

[520 rows x 1 columns]

In [55]:
run_experiment(
    client=sonnet_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "sonnet_google_ux.csv"), index_col=0),
    save_to="pm_520_sonnet_twice_modified_cvs_google_ux.csv",
)

Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...
Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...
Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...
Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...

      Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Skills\n\n- Wiref...
6021   PROFESSIONAL SUMMARY\n\nOver 50 Websites\nMore...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n**Multilingual Professiona...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\nTeam Lead - Email M...
16064  # Professional Summary\n\nResults-driven e-com...

[520 rows x 1 columns]

#### And for a third time with Sonnet 4.5

In [251]:
run_experiment(
    client=sonnet_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "twice_sonnet_doordash_pm.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "thrice_sonnet_doordash_pm.csv")
)

run_experiment(
    client=sonnet_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "twice_sonnet_google_ux.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "thrice_sonnet_google_ux.csv")
)

Batch msgbatch_015pHan3RkDc7iDjPPyVMSjV is still processing...
Batch msgbatch_015pHan3RkDc7iDjPPyVMSjV is still processing...
Batch msgbatch_015pHan3RkDc7iDjPPyVMSjV is still processing...
Batch msgbatch_015pHan3RkDc7iDjPPyVMSjV is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...
Batch msgbatch_013Zrqij5WY1qNZyMfyRySzB is still processing...

      Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Skills\n\nWirefra...
6021   **PROFESSIONAL SUMMARY**\n\nOver 50 Websites |...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n**Multilingual Professiona...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\nTeam Lead - Email M...
16064  # Professional Summary\n\nResults-driven e-com...

[520 rows x 1 columns]

#### And a fourth time with Sonnet 4.5

In [254]:
run_experiment(
    client=sonnet_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "thrice_sonnet_doordash_pm.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "fourth_sonnet_doordash_pm.csv")
)

run_experiment(
    client=sonnet_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "thrice_sonnet_google_ux.csv"), index_col=0),
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "fourth_sonnet_google_ux.csv")
)

Batch msgbatch_01Cv49LRMJMmY2YGCtwr8pN8 is still processing...
Batch msgbatch_01Cv49LRMJMmY2YGCtwr8pN8 is still processing...
Batch msgbatch_01Cv49LRMJMmY2YGCtwr8pN8 is still processing...
Batch msgbatch_01Cv49LRMJMmY2YGCtwr8pN8 is still processing...
Batch msgbatch_01Cv49LRMJMmY2YGCtwr8pN8 is still processing...
Batch msgbatch_01Cv49LRMJMmY2YGCtwr8pN8 is still processing...
Batch msgbatch_01M9jYDLBbSkNTpE7cM17aK4 is still processing...
Batch msgbatch_01M9jYDLBbSkNTpE7cM17aK4 is still processing...
Batch msgbatch_01M9jYDLBbSkNTpE7cM17aK4 is still processing...
Batch msgbatch_01M9jYDLBbSkNTpE7cM17aK4 is still processing...
Batch msgbatch_01M9jYDLBbSkNTpE7cM17aK4 is still processing...

      Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Skills\n\nWirefra...
6021   **PROFESSIONAL SUMMARY**\n\nOver 50 Websites |...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n**Multilingual Professiona...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\nTeam Lead - Email M...
16064  # Professional Summary\n\nResults-driven e-com...

[520 rows x 1 columns]

# And Sonnet 3.5

Krijgt een error dat sonnet 3.5 niet beschikbaar is. Op de website staat ook dat hij depricated is.

In [244]:
sonnet_3_5_modification_client_doordash = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-sonnet-3-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

sonnet_3_5_modification_client_google_ux = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-sonnet-3-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name, 
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [245]:
modified_cvs_sonnet_3_5_doordash = run_experiment(
    sonnet_3_5_modification_client_doordash,
    uiux_pm_520_df,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "sonnet_3_5_doordash.csv"),
)

Batch msgbatch_01YFKfksMp49Ss2EK9JQtUX7 is still processing...
Batch msgbatch_01YFKfksMp49Ss2EK9JQtUX7 is still processing...
Server error 0
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 1
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 2
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 3
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 4
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 5
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 6
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 7
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 8
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 9
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 10
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 11
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 12
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 13
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 14
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 15
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 16
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 17
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 18
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 19
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 20
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 21
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 22
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 23
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 24
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 25
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 26
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 27
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 28
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 29
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 30
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 31
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 32
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 33
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 34
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 35
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 36
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 37
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 38
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 39
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 40
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 41
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 42
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 43
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 44
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 45
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 46
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 47
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 48
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 49
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 50
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 51
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 52
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 53
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 54
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 55
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 56
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 57
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 58
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 59
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 60
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 61
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 62
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 63
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 64
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 65
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 66
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 67
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 68
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 69
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 70
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 71
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 72
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 73
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 74
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 75
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 76
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 77
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 78
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 79
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 80
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 81
Error details: {'error': BetaErrorResponse(error=BetaNotFoundError(message='model: claude-sonnet-3-5', type='not_found_error', details={'error_visibility': 'user_facing'}), request_id=None, type='error'), 'type': 'errored'}
Server error 82

In [ ]:
modified_cvs_sonnet_3_5_google_ux = run_experiment(
    sonnet_3_5_modification_client_google_ux,
    uiux_pm_520_df,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "sonnet_3_5_google_ux.csv"),
)

Batch msgbatch_01CjAfNEbSdXcCFj4GDBrWBW is still processing...

KeyboardInterrupt:

In [ ]:
twice_modified_cvs_sonnet_3_5_doordash = run_experiment(
    client=sonnet_3_5_modification_client_doordash,
    df=modified_cvs_sonnet_3_5_doordash,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_sonnet_3_5_doordash.csv"),
)

In [ ]:
twice_modified_cvs_sonnet_3_5_google_ux = run_experiment(
    client=sonnet_3_5_modification_client_google_ux,
    df=modified_cvs_sonnet_3_5_google_ux,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_sonnet_3_5_google_ux.csv"),
)

# And OpenAI's GPT-5.2

In [15]:
gpt_4_2_modification_client_doordash = modify_cv2.OpenAIClient(
    input_api_key=api_keys["openai"],
    model="gpt-5.2-2025-12-11",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gpt_4_2_modification_client_google_ux = modify_cv2.OpenAIClient(
    input_api_key=api_keys["openai"],
    model="gpt-5.2-2025-12-11",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [35]:
run_experiment(
    gpt_4_2_modification_client_google_ux,
    uiux_pm_520_df,
    save_to="gpt_4_2_google_ux_original_prompt_modified_cvs.csv",
)

run_experiment(
    gpt_4_2_modification_client_doordash,
    uiux_pm_520_df,
    save_to="gpt_4_2_doordash_original_prompt_modified_cvs.csv",
)

Processing 520 CVs in 3 batch(es)
Processing chunk 1/3 (242 CVs)
Batch batch_6967cddc52488190b33c1fc4fd378800 is still validating...

KeyboardInterrupt:

# And Gemini Flash 3 (Preview)

In [58]:
def start_experiment_gemini(
    client, df: pd.DataFrame = uiux_pm_520_df
) -> str:
    if len(df.columns) == 1:
        df_just_cvs = df[[df.columns[0]]].copy()
    elif "CV" in df.columns:
        df_just_cvs = df[["CV"]].copy()
    else:
        raise ValueError("DataFrame must have either one column or a column named 'CV'")
    batch_id = client.start_batch(df_just_cvs)
    return batch_id


def finish_experiment_gemini(client, batch_id: str, save_to: str, df: pd.DataFrame = uiux_pm_520_df) -> pd.DataFrame:
    if len(df.columns) == 1:
        df_just_cvs = df[[df.columns[0]]].copy()
    elif "CV" in df.columns:
        df_just_cvs = df[["CV"]].copy()
    else:
        raise ValueError("DataFrame must have either one column or a column named 'CV'")
    df_modified_cvs = client.get_batch_results(batch_id, df_just_cvs)
    df_modified_cvs.to_csv(save_to)
    return df_modified_cvs

In [240]:
gemini_flash_3_preview_modification_client_doordash = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-flash-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gemini_flash_3_preview_modification_client_google_ux = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-flash-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [ ]:
flash_3_batch_id_google_ux = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_google_ux,
)

In [29]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_google_ux,
    batch_id=flash_3_batch_id_google_ux,
    save_to="uiux_pm_520_gemini_flash_3_modified_cvs_google_ux.csv",
)

Batch batches/8zfff4num44a3bvrehktp4vxvs0kyfsk246s current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-flash-preview_of_CV_Modelgemini-3-flash-preview
6018   **[NAME]**\n[Phone Number] | [Email Address] |...
6021   **[YOUR NAME]**\n[Your Phone Number] | [Your E...
6026   **[NAME]**\nLead Product Designer | UI/UX & Br...
9479   **[YOUR NAME]**\n[Phone Number] | [Email Addre...
16980  **Depositphotos | Content Researcher**\n\n* Re...
...                                                  ...
15679  DARIA MALININA\n\nPROFESSIONAL SUMMARY\nHighly...
15743  **LEAD CLOUD ARCHITECT**\n\n**Professional Pro...
16036  [NAME]\n[PHONE NUMBER] | [EMAIL] | [LINKEDIN P...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **CHIEF MARKETING OFFICER / RELEASE MANAGER**\...

[520 rows x 1 columns]

In [16]:
flash_3_batch_id_doordash = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_doordash,
)

print("Gemini Flash 3 Batch ID:", flash_3_batch_id_doordash)

Creating batch job for 520 CVs...
Batch job created: batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok
Use get_batch_results('batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok') to retrieve results when complete
Gemini Flash 3 Batch ID: batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok

In [30]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_doordash,
    batch_id=flash_3_batch_id_doordash,
    save_to="uiux_pm_520_gemini_flash_3_modified_cvs_doordash.csv",
)

Batch batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-flash-preview_of_CV_Modelgemini-3-flash-preview
6018   **Web and UX/UI Designer**\n\n**PROFESSIONAL S...
6021   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
6026   **SENIOR PRODUCT & UI/UX DESIGNER**\n\n**Profe...
9479   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **LEAD CLOUD ARCHITECT**\n\n**Professional Pro...
16036  **PROFESSIONAL SUMMARY**\n\nAccomplished marke...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **[NAME]**\n**[CONTACT INFORMATION]**\n\n**PRO...

[520 rows x 1 columns]

#### And do it once more with the same model and prompts

In [60]:
twice_gemini_flash_doordash_batch_id = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_doordash_pm.csv"), index_col=0),
)

print("Gemini Flash 3 Twice Batch ID:", twice_gemini_flash_doordash_batch_id)

twice_gemini_flash_google_ux_batch_id = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_google_ux.csv"), index_col=0),
)

print("Gemini Flash 3 Twice Batch ID:", twice_gemini_flash_google_ux_batch_id)

Creating batch job for 520 CVs...
Batch job created: batches/g1ko7xz7tmyfzhz9rynbmaqywfd8vvqgg2um
Use get_batch_results('batches/g1ko7xz7tmyfzhz9rynbmaqywfd8vvqgg2um') to retrieve results when complete
Gemini Flash 3 Twice Batch ID: batches/g1ko7xz7tmyfzhz9rynbmaqywfd8vvqgg2um
Creating batch job for 520 CVs...
Batch job created: batches/fkawyntaqe6vli58948dvi76yr4ezxmih2zv
Use get_batch_results('batches/fkawyntaqe6vli58948dvi76yr4ezxmih2zv') to retrieve results when complete
Gemini Flash 3 Twice Batch ID: batches/fkawyntaqe6vli58948dvi76yr4ezxmih2zv

In [217]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_doordash,
    batch_id=twice_gemini_flash_doordash_batch_id,
    save_to="pm_520_gemini_flash_twice_modified_cvs_doordash.csv",
)

Batch batches/g1ko7xz7tmyfzhz9rynbmaqywfd8vvqgg2um current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-flash-preview_of_CV_Modelgemini-3-flash-preview
6018   **Web and UX/UI Designer**\n\n**PROFESSIONAL S...
6021   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
6026   **SENIOR PRODUCT & UI/UX DESIGNER**\n\n**SUMMA...
9479   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **[NAME]**\n[Phone Number] | [Email Address] |...
16036  **[NAME]**\n[Contact Information]\n\n**PROFESS...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **[NAME]**\n**[CONTACT INFORMATION]**\n\n**PRO...

[520 rows x 1 columns]

In [218]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_google_ux,
    batch_id=twice_gemini_flash_google_ux_batch_id,
    save_to="pm_520_gemini_flash_twice_modified_cvs_google_ux.csv",
)

Batch batches/fkawyntaqe6vli58948dvi76yr4ezxmih2zv current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-flash-preview_of_CV_Modelgemini-3-flash-preview
6018   **[NAME]**\n[Phone Number] | [Email Address] |...
6021   **[YOUR NAME]**\n[Your Phone Number] | [Your E...
6026   **[NAME]**\nLead Product Designer | UI/UX & Br...
9479   **[YOUR NAME]**\n[Phone Number] | [Email Addre...
16980  **Depositphotos | Content Researcher**\n\n* Cu...
...                                                  ...
15679  DARIA MALININA\n\nPROFESSIONAL SUMMARY\nHighly...
15743  **LEAD CLOUD ARCHITECT**\n\n**Professional Pro...
16036  [NAME]\n[PHONE NUMBER] | [EMAIL] | [LINKEDIN P...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **[NAME]**\n[Phone Number] | [Email Address]\n...

[520 rows x 1 columns]

# And Gemini Pro 3 (Preview)

In [63]:

gemini_pro_3_preview_modification_client_doordash = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-pro-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gemini_pro_3_preview_modification_client_google_ux = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-pro-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [19]:

pro_3_batch_id_doordash = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_doordash,
)

print("Gemini Pro 3 Batch ID:", pro_3_batch_id_doordash)

Creating batch job for 520 CVs...
Batch job created: batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6
Use get_batch_results('batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6') to retrieve results when complete
Gemini Pro 3 Batch ID: batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6

In [36]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    batch_id=pro_3_batch_id_doordash,
    save_to="uiux_pm_520_gemini_pro_3_modified_cvs_doordash.csv",
)

Batch batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6 current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   **PROFESSIONAL SUMMARY**\n\nDedicated Web and ...
6021   **HEAD OF DESIGN**\n\n**PROFESSIONAL SUMMARY**...
6026   **Senior Product & Brand Designer**\n\n**Profe...
9479   [Name]\n[Phone Number] | [Email Address] | [Po...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**PROFESSIONAL SUMMARY**...
15743  **PROFESSIONAL SUMMARY**\n\nLead Cloud Archite...
16036  **PROFESSIONAL SUMMARY**\n\nSenior Marketing a...
16039  **Team Lead - Email Marketing**\n**Digital Con...
16064  **PROFESSIONAL SUMMARY**\n\nResults-oriented C...

[520 rows x 1 columns]

In [21]:


pro_3_batch_id_google_ux = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_google_ux,
)

print("Gemini Pro 3 Batch ID:", pro_3_batch_id_google_ux)

Creating batch job for 520 CVs...
Batch job created: batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb
Use get_batch_results('batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb') to retrieve results when complete
Gemini Pro 3 Batch ID: batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb

In [37]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    batch_id=pro_3_batch_id_google_ux,
    save_to="uiux_pm_520_gemini_pro_3_modified_cvs_google_ux.csv",
)

Batch batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   [Name]\n[Phone Number] | [Email Address] | [Po...
6021   **HEAD OF DESIGN DEPARTMENT**\n\n**SUMMARY OF ...
6026   [Your Name]\n[Your Contact Information: Phone ...
9479   **[Your Name]**\n[City, State/Country] | [Phon...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **PROFESSIONAL SUMMARY**\n\nLead Cloud Archite...
16036  **PROFESSIONAL SUMMARY**\n\nStrategic Marketin...
16039  **PROFESSIONAL EXPERIENCE**\n\n**Digital Conne...
16064  **PROFESSIONAL SUMMARY**\n\nResults-oriented C...

[520 rows x 1 columns]

#### And a second modification with the same prompts and model

In [64]:
gemini_pro_doordash_twice_batch_id = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_pro_doordash_pm.csv"), index_col=0),
)

print("Gemini Pro 3 Twice Batch ID:", gemini_pro_doordash_twice_batch_id)

gemini_pro_google_ux_twice_batch_id = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_pro_google_ux.csv"), index_col=0),
)

print("Gemini Pro 3 Twice Batch ID:", gemini_pro_google_ux_twice_batch_id)

Creating batch job for 520 CVs...
Batch job created: batches/h1nqu6e3wzpd1wri1bs11misp1x9gyfw1em9
Use get_batch_results('batches/h1nqu6e3wzpd1wri1bs11misp1x9gyfw1em9') to retrieve results when complete
Gemini Pro 3 Twice Batch ID: batches/h1nqu6e3wzpd1wri1bs11misp1x9gyfw1em9
Creating batch job for 520 CVs...
Batch job created: batches/zpjk3tjexh8ukyoxwu7yjg6qbewlwlkawk25
Use get_batch_results('batches/zpjk3tjexh8ukyoxwu7yjg6qbewlwlkawk25') to retrieve results when complete
Gemini Pro 3 Twice Batch ID: batches/zpjk3tjexh8ukyoxwu7yjg6qbewlwlkawk25

In [102]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    batch_id=gemini_pro_doordash_twice_batch_id,
    save_to="pm_520_gemini_pro_twice_modified_cvs_doordash.csv",
)

Batch batches/h1nqu6e3wzpd1wri1bs11misp1x9gyfw1em9 current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   **PROFESSIONAL SUMMARY**\n\nDedicated Web and ...
6021   **HEAD OF DESIGN**\n\n**PROFESSIONAL SUMMARY**...
6026   **Senior Product & Brand Designer**\n\n**Profe...
9479   [Name]\n[Phone Number] | [Email Address] | [Po...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**PROFESSIONAL SUMMARY**...
15743  **PROFESSIONAL SUMMARY**\n\nLead Cloud Archite...
16036  **SENIOR MARKETING & STRATEGY PROFESSIONAL**\n...
16039  **Team Lead - Email Marketing**\n**Digital Con...
16064  **PROFESSIONAL SUMMARY**\n\nE-commerce executi...

[520 rows x 1 columns]

In [93]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    batch_id=gemini_pro_google_ux_twice_batch_id,
    save_to="pm_520_gemini_pro_twice_modified_cvs_google_ux.csv",
)

Batch batches/zpjk3tjexh8ukyoxwu7yjg6qbewlwlkawk25 current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   [Name]\n[Phone Number] | [Email Address] | [Po...
6021   **HEAD OF DESIGN DEPARTMENT**\n\n**SUMMARY OF ...
6026   [Your Name]\n[Your Contact Information: Phone ...
9479   **[Your Name]**\n[City, State/Country] | [Phon...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **PROFESSIONAL SUMMARY**\n\nLead Cloud Archite...
16036  **[Your Name]**\n[City, State/Country] | [Phon...
16039  **PROFESSIONAL EXPERIENCE**\n\n**Digital Conne...
16064  **PROFESSIONAL SUMMARY**\n\nDynamic Chief Mark...

[520 rows x 1 columns]

# One modification with Haiku 4.5, then one with Opus 4.5

In [134]:
once_modified_haiku_doordash_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "haiku_doordash_pm.csv"), index_col=0
)
once_modified_haiku_google_ux_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "haiku_google_ux.csv"), index_col=0
)

In [135]:
run_experiment(
    df=once_modified_haiku_doordash_df,
    client=opus_4_5_modification_client_doordash,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_haiku_opus_doordash_pm.csv"),
)

Batch msgbatch_0134MNqjDVx2FqcfKghoSCzi is still processing...
Batch msgbatch_0134MNqjDVx2FqcfKghoSCzi is still processing...
Batch msgbatch_0134MNqjDVx2FqcfKghoSCzi is still processing...
Batch msgbatch_0134MNqjDVx2FqcfKghoSCzi is still processing...
Batch msgbatch_0134MNqjDVx2FqcfKghoSCzi is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-opus-4-5
6018   **Web & UX/UI Designer**\n\n**Professional Sum...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\n- 50+ W...
6026   # Design Professional\n\n## Professional Summa...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **PROFESSIONAL EXPERIENCE**\n\n**Depositphotos...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL PROFILE\n\...
15743  # Cloud Architect\n\n## Core Expertise\n\nEnte...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**T...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

In [136]:
run_experiment(
    df=once_modified_haiku_google_ux_df,
    client=opus_4_5_modification_client_google_ux,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_haiku_opus_google_ux.csv"),
)

Batch msgbatch_01LVe3sM6izrzkz86LhWKDy3 is still processing...
Batch msgbatch_01LVe3sM6izrzkz86LhWKDy3 is still processing...
Batch msgbatch_01LVe3sM6izrzkz86LhWKDy3 is still processing...
Batch msgbatch_01LVe3sM6izrzkz86LhWKDy3 is still processing...
Batch msgbatch_01LVe3sM6izrzkz86LhWKDy3 is still processing...
Batch msgbatch_01LVe3sM6izrzkz86LhWKDy3 is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-opus-4-5
6018   **WEB AND UX/UI DESIGNER**\n\n**CORE COMPETENC...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\n\nOver ...
6026   # PROFESSIONAL SUMMARY\n\nDesign Professional ...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **PROFESSIONAL EXPERIENCE**\n\n**Content Resea...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\nR...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**T...
16064  # Professional Resume\n\n## E-Commerce Product...

[520 rows x 1 columns]

# Sonnet 4.5 en daarna Opus 4.5

In [137]:
once_modified_sonnet_doordash_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "sonnet_doordash_pm.csv"), index_col=0
)
once_modified_sonnet_google_ux_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "sonnet_google_ux.csv"), index_col=0
)

In [138]:
run_experiment(
    client=opus_4_5_modification_client_doordash,
    df=once_modified_sonnet_doordash_df,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_sonnet_opus_doordash_pm.csv"),
)

Batch msgbatch_01CLbi7bbpzaPuW9Sqo7vYR1 is still processing...
Batch msgbatch_01CLbi7bbpzaPuW9Sqo7vYR1 is still processing...
Batch msgbatch_01CLbi7bbpzaPuW9Sqo7vYR1 is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-opus-4-5
6018   # Web & UX/UI Designer\n\n## Professional Expe...
6021   OVER 50 WEBSITES\nMORE THAN 30 LOGOTYPES\n4 MO...
6026   # PROFESSIONAL SUMMARY\n\nDesign leader with 1...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n---\n...
16980  **Content Researcher**\nDepositphotos\n\n• Res...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\n\...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\nMarketing and operat...
16039  **PROFESSIONAL EXPERIENCE**\n\n**Team Lead – E...
16064  **PROFESSIONAL SUMMARY**\n\nResults-driven mar...

[520 rows x 1 columns]

In [139]:
run_experiment(
    client=opus_4_5_modification_client_google_ux,
    df=once_modified_sonnet_google_ux_df,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_sonnet_opus_google_ux.csv"),
)

Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...
Batch msgbatch_011zsU328pEsiWKMsrNBckaU is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-opus-4-5
6018   # Web & UX/UI Designer\n\n## Professional Expe...
6021   **PROFESSIONAL SUMMARY**\n\nVisual designer an...
6026   # PROFESSIONAL SUMMARY\n\nDesign leader with 1...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **PROFESSIONAL EXPERIENCE**\n\n**Depositphotos...
...                                                  ...
15679  # DARIA MALININA\n\n**Multilingual Professiona...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\nSenior marketing and...
16039  PROFESSIONAL EXPERIENCE\n\nTeam Lead - Email M...
16064  # Professional Summary\n\nResults-driven e-com...

[520 rows x 1 columns]

# Flash 3.0 en daarna Pro 3.0

In [140]:
once_modified_gemini_flash_doordash_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_doordash_pm.csv"), index_col=0
)
once_modified_gemini_flash_google_ux_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_google_ux.csv"), index_col=0
)

In [141]:
second_modification_gemini_pro_doordash_batch_id = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_doordash,
    df=once_modified_gemini_flash_doordash_df,
)

second_modification_gemini_pro_google_ux_batch_id = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_google_ux,
    df=once_modified_gemini_flash_google_ux_df,
)

print("Gemini Pro Second Modification DoorDash Batch ID:", second_modification_gemini_pro_doordash_batch_id)
print("Gemini Pro Second Modification Google UX Batch ID:", second_modification_gemini_pro_google_ux_batch_id)

Creating batch job for 520 CVs...
Batch job created: batches/pmndnknvvi7cow7opqe5gtlhm6nsmtnrzkg1
Use get_batch_results('batches/pmndnknvvi7cow7opqe5gtlhm6nsmtnrzkg1') to retrieve results when complete
Creating batch job for 520 CVs...
Batch job created: batches/cdz2n7boturxv2stybqfe8okxkyujot3vp09
Use get_batch_results('batches/cdz2n7boturxv2stybqfe8okxkyujot3vp09') to retrieve results when complete
Gemini Pro Second Modification DoorDash Batch ID: batches/pmndnknvvi7cow7opqe5gtlhm6nsmtnrzkg1
Gemini Pro Second Modification Google UX Batch ID: batches/cdz2n7boturxv2stybqfe8okxkyujot3vp09

In [161]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    batch_id=second_modification_gemini_pro_doordash_batch_id,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_gemini_flash_pro_doordash_pm.csv"),
)

Batch batches/pmndnknvvi7cow7opqe5gtlhm6nsmtnrzkg1 current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018                           not_successfully_modified
6021   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
6026   **SENIOR PRODUCT & UI/UX DESIGNER**\n\n**PROFE...
9479   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **LEAD CLOUD ARCHITECT**\n\n**PROFESSIONAL PRO...
16036  **[Your Name]**\n[Phone Number] | [Email Addre...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **[NAME]**\n**[CONTACT INFORMATION]**\n\n**PRO...

[520 rows x 1 columns]

In [162]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    batch_id=second_modification_gemini_pro_google_ux_batch_id,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_gemini_flash_pro_google_ux.csv"),
)

Batch batches/cdz2n7boturxv2stybqfe8okxkyujot3vp09 current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   **[NAME]**\n[Phone Number] | [Email Address] |...
6021   **[YOUR NAME]**\n[Your Phone Number] | [Your E...
6026   **[NAME]**\nLead Product Designer | UI/UX & Br...
9479   **[YOUR NAME]**\n[Phone Number] | [Email Addre...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **LEAD CLOUD ARCHITECT**\n\n**PROFESSIONAL PRO...
16036                          not_successfully_modified
16039                          not_successfully_modified
16064  **CHIEF MARKETING OFFICER / RELEASE MANAGER**\...

[520 rows x 1 columns]

# Nog een gemini, Pro 2.0 misschien
### Eén keer modifyen dan

In [168]:
gemini_2_flash_lite_modification_client_doordash = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-2.0-flash-lite",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gemini_2_flash_lite_modification_client_google_ux = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-2.0-flash-lite",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [ ]:
gemini_2_flash_lite_batch_id_doordash = start_experiment_gemini(
    client=gemini_2_flash_lite_modification_client_doordash,
    df=uiux_pm_520_df,
)

Creating batch job for 520 CVs...
Batch job created: batches/rzxdr6mwyfjxvldsizehc82r2y8cg1bz29ui
Use get_batch_results('batches/rzxdr6mwyfjxvldsizehc82r2y8cg1bz29ui') to retrieve results when complete

'batches/rzxdr6mwyfjxvldsizehc82r2y8cg1bz29ui'

In [172]:
gemini_2_flash_lite_batch_id_google_ux = start_experiment_gemini(
    gemini_2_flash_lite_modification_client_google_ux,
    df=uiux_pm_520_df
)

Creating batch job for 520 CVs...
Batch job created: batches/qxmklj2mw8trv4fz1pejglj8v9psu3hofl6h
Use get_batch_results('batches/qxmklj2mw8trv4fz1pejglj8v9psu3hofl6h') to retrieve results when complete

In [174]:
flash_3_preview_mistake_batch_id = 'batches/lbhfyrqcz1mcagfninifafq7gzxr2tzfg6r2'
gemini_2_flash_lite_batch_id_doordash = 'batches/rzxdr6mwyfjxvldsizehc82r2y8cg1bz29ui'

In [175]:
finish_experiment_gemini(
    client=gemini_2_flash_lite_modification_client_doordash,
    batch_id=gemini_2_flash_lite_batch_id_doordash,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_lite_doordash_pm.csv"),
)

Batch batches/rzxdr6mwyfjxvldsizehc82r2y8cg1bz29ui current state: JOB_STATE_SUCCEEDED

      Modified_gemini-2.0-flash-lite_of_CV_Modelgemini-2.0-flash-lite
6018   **Summary**\n\nWeb Designer with experience in...
6021   **[Your Name]**\n[Your Phone Number] | [Your E...
6026   **[Your Name]**\n\n**Summary**\n\nDesign profe...
9479   **Summary**\n\nResults-oriented graphic design...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**Summary**\n\nHighly mo...
15743  **Summary**\n\nResults-oriented Cloud Architec...
16036  **[Your Name]**\n\n**Summary**\n\nResults-orie...
16039  **Team Lead - Email Marketing**\nDigital Conne...
16064  **Summary**\n\nResults-oriented professional w...

[520 rows x 1 columns]

In [176]:
finish_experiment_gemini(
    client=gemini_2_flash_lite_modification_client_google_ux,
    batch_id=gemini_2_flash_lite_batch_id_google_ux,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_lite_google_ux.csv"),
)

Batch batches/qxmklj2mw8trv4fz1pejglj8v9psu3hofl6h current state: JOB_STATE_SUCCEEDED

      Modified_gemini-2.0-flash-lite_of_CV_Modelgemini-2.0-flash-lite
6018   **Summary**\n\nWeb designer experienced in web...
6021   **\[Your Name]**\n\[Your Phone Number] | \[You...
6026   **[Your Name]**\n\n**Summary**\n\nDesign profe...
9479   **[Your Name]**\n[Your Phone Number] | [Your E...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**Summary**\n\nHighly mo...
15743  **Summary**\n\nResults-oriented Cloud Architec...
16036  **[Your Name]**\n\n**Summary**\n\nResults-orie...
16039  **Team Lead - Email Marketing**\nDigital Conne...
16064  **Summary**\n\nResults-oriented professional w...

[520 rows x 1 columns]

# En ook twee keer met Flash Lite 2.0

In [177]:
once_modified_gemini_2_flash_lite_doordash_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_lite_doordash_pm.csv"), index_col=0
)
once_modified_gemini_2_flash_lite_google_ux_df = pd.read_csv(
    os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_lite_google_ux.csv"), index_col=0
)

In [178]:
second_modification_gemini_2_flash_lite_doordash_batch_id = start_experiment_gemini(
    gemini_2_flash_lite_modification_client_doordash,
    df=once_modified_gemini_2_flash_lite_doordash_df,
)

second_modification_gemini_2_flash_lite_google_ux_batch_id = start_experiment_gemini(
    gemini_2_flash_lite_modification_client_google_ux,
    df=once_modified_gemini_2_flash_lite_google_ux_df,
)
print("Gemini 2.0 Flash Lite Second Modification DoorDash Batch ID:", second_modification_gemini_2_flash_lite_doordash_batch_id)
print("Gemini 2.0 Flash Lite Second Modification Google UX Batch ID:", second_modification_gemini_2_flash_lite_google_ux_batch_id)

Creating batch job for 520 CVs...
Batch job created: batches/7g4snqgl1rn9h1l76nt2po1wzxyhzv466zma
Use get_batch_results('batches/7g4snqgl1rn9h1l76nt2po1wzxyhzv466zma') to retrieve results when complete
Creating batch job for 520 CVs...
Batch job created: batches/h07quajhmu9hrjdlwhd6wky4enwa7l99vfns
Use get_batch_results('batches/h07quajhmu9hrjdlwhd6wky4enwa7l99vfns') to retrieve results when complete
Gemini 2.0 Flash Lite Second Modification DoorDash Batch ID: batches/7g4snqgl1rn9h1l76nt2po1wzxyhzv466zma
Gemini 2.0 Flash Lite Second Modification Google UX Batch ID: batches/h07quajhmu9hrjdlwhd6wky4enwa7l99vfns

In [188]:
finish_experiment_gemini(
    client=gemini_2_flash_lite_modification_client_doordash,
    batch_id=second_modification_gemini_2_flash_lite_doordash_batch_id,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_gemini_2_flash_lite_doordash_pm.csv"),
)

Batch batches/7g4snqgl1rn9h1l76nt2po1wzxyhzv466zma current state: JOB_STATE_SUCCEEDED

      Modified_gemini-2.0-flash-lite_of_CV_Modelgemini-2.0-flash-lite
6018   **Summary**\n\nWeb Designer experienced in web...
6021   **[Your Name]**\n[Your Phone Number] | [Your E...
6026   **[Your Name]**\n\n**Summary**\n\nDesign profe...
9479   **Summary**\n\nResults-driven graphic designer...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**Summary**\n\nResults-o...
15743  **Summary**\n\nResults-focused Cloud Architect...
16036  **[Your Name]**\n\n**Summary**\n\nResults-orie...
16039  **Team Lead - Email Marketing**\nDigital Conne...
16064  **Summary**\n\nResults-driven professional wit...

[520 rows x 1 columns]

In [189]:
finish_experiment_gemini(
    client=gemini_2_flash_lite_modification_client_google_ux,
    batch_id=second_modification_gemini_2_flash_lite_google_ux_batch_id,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_gemini_2_flash_lite_google_ux.csv"),
)

Batch batches/h07quajhmu9hrjdlwhd6wky4enwa7l99vfns current state: JOB_STATE_SUCCEEDED

      Modified_gemini-2.0-flash-lite_of_CV_Modelgemini-2.0-flash-lite
6018   **Summary**\n\nResults-oriented Web Designer w...
6021   **[Your Name]**\n[Your Phone Number] | [Your E...
6026   **[Your Name]**\n\n**Summary**\n\nDesign profe...
9479   **[Your Name]**\n[Your Phone Number] | [Your E...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**Summary**\n\nResults-o...
15743  **Summary**\n\nResults-driven Cloud Architect ...
16036  **[Your Name]**\n\n**Summary**\n\nResults-orie...
16039  **Team Lead - Email Marketing**\nDigital Conne...
16064  **Summary**\n\nResults-driven professional wit...

[520 rows x 1 columns]

# En dan die gemini 2 flash lite modificatie nog een keer door Pro 3.0 laten doen.

In [184]:
second_gemini_pro_modification_after_flash_lite_batch_id_doordash = start_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    df=once_modified_gemini_2_flash_lite_doordash_df,
)

print("Gemini Pro Second Modification After Flash Lite DoorDash Batch ID:", second_gemini_pro_modification_after_flash_lite_batch_id_doordash)

second_gemini_pro_modification_after_flash_lite_batch_id_google_ux = start_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    df=once_modified_gemini_2_flash_lite_google_ux_df,
)

print("Gemini Pro Second Modification After Flash Lite Google UX Batch ID:", second_gemini_pro_modification_after_flash_lite_batch_id_google_ux)

Creating batch job for 520 CVs...
Batch job created: batches/2s2zl1t8d7yhyzruhtm7m0wr3f7a6ueyt1go
Use get_batch_results('batches/2s2zl1t8d7yhyzruhtm7m0wr3f7a6ueyt1go') to retrieve results when complete
Gemini Pro Second Modification After Flash Lite DoorDash Batch ID: batches/2s2zl1t8d7yhyzruhtm7m0wr3f7a6ueyt1go
Creating batch job for 520 CVs...
Batch job created: batches/q5a5hn655ht9jwnn8vs750vfjtjfo37dnr2u
Use get_batch_results('batches/q5a5hn655ht9jwnn8vs750vfjtjfo37dnr2u') to retrieve results when complete
Gemini Pro Second Modification After Flash Lite Google UX Batch ID: batches/q5a5hn655ht9jwnn8vs750vfjtjfo37dnr2u

In [213]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    batch_id=second_gemini_pro_modification_after_flash_lite_batch_id_doordash,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_gemini_flash_lite_pro_doordash_pm.csv"),
)

Batch batches/2s2zl1t8d7yhyzruhtm7m0wr3f7a6ueyt1go current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   **[Your Name]**\n[Your Phone Number] | [Your E...
6021   **[Your Name]**\n[Your Phone Number] | [Your E...
6026   **[Your Name]**\n\n**Professional Summary**\n\...
9479   **Summary**\n\nAccomplished Graphic and UI/UX ...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **Summary**\n\nResults-oriented Cloud Architec...
16036  **[Your Name]**\n\n**PROFESSIONAL SUMMARY**\n\...
16039  **Digital Connect Ukraine** (IT Consulting / S...
16064  **SUMMARY**\n\nResults-oriented professional w...

[520 rows x 1 columns]

In [236]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    batch_id=second_gemini_pro_modification_after_flash_lite_batch_id_google_ux,
    save_to=os.path.join(MODIFIED_CVS_FOLDER, "twice_gemini_flash_lite_pro_google_ux.csv"),
)

Batch batches/q5a5hn655ht9jwnn8vs750vfjtjfo37dnr2u current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   **Summary**\n\nUser-focused Web Designer with ...
6021   **[Your Name]**\n[Your Phone Number] | [Your E...
6026   **[Your Name]**\n\n**Summary**\n\nAccomplished...
9479   **[Your Name]**\n[Your Phone Number] | [Your E...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**PROFESSIONAL SUMMARY**...
15743  **SUMMARY**\n\nResults-oriented Lead Cloud Arc...
16036  **[Your Name]**\n\n**Professional Summary**\n\...
16039  **[Name]**\n[Phone Number] | [Email Address] |...
16064  **SUMMARY**\n\nResults-oriented professional w...

[520 rows x 1 columns]

# Sommigen zijn niet 100p goed gedaan

Bijvoorbeeld bij de Gemini modellen is het resultaat vaak `"not_successfully_modified"` geworden. Maar dat hoeft niet te betekenen dat er wat fout is gegaan, dat geeft hij ook als het format niet helemaal is wat we verwachten.

Dit zijn de batches: 

Een keer Flash

batches/8zfff4num44a3bvrehktp4vxvs0kyfsk246s

batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok

Twee keer Flash

batches/g1ko7xz7tmyfzhz9rynbmaqywfd8vvqgg2um

batches/fkawyntaqe6vli58948dvi76yr4ezxmih2zv

Een keer Pro

batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6

batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb

Twee keer Pro

batches/h1nqu6e3wzpd1wri1bs11misp1x9gyfw1em9

batches/zpjk3tjexh8ukyoxwu7yjg6qbewlwlkawk25

Flash dan Pro

batches/pmndnknvvi7cow7opqe5gtlhm6nsmtnrzkg1

batches/cdz2n7boturxv2stybqfe8okxkyujot3vp09

Flash Lite dan Pro
batches/2s2zl1t8d7yhyzruhtm7m0wr3f7a6ueyt1go
batches/q5a5hn655ht9jwnn8vs750vfjtjfo37dnr2u

Een keer Flash Lite

batches/rzxdr6mwyfjxvldsizehc82r2y8cg1bz29ui

batches/qxmklj2mw8trv4fz1pejglj8v9psu3hofl6h

Twee keer Flash Lite

batches/7g4snqgl1rn9h1l76nt2po1wzxyhzv466zma

batches/h07quajhmu9hrjdlwhd6wky4enwa7l99vfns

In [253]:
nsm = []
gemini_flash_3_preview_modification_client_doordash.get_batch_results(
    batch_id="batches/8zfff4num44a3bvrehktp4vxvs0kyfsk246s",
    cv_s_dataframe=uiux_pm_520_df[["CV"]],
    nsm=nsm
)
nsm

Batch batches/8zfff4num44a3bvrehktp4vxvs0kyfsk246s current state: JOB_STATE_SUCCEEDED

[{'response': {'candidates': [{'finishReason': 'STOP',
     'index': 0,
     'content': {}}],
   'responseId': 'CBRoab_HOo_O_uMP_9jLyAs',
   'usageMetadata': {'thoughtsTokenCount': 1357,
    'promptTokensDetails': [{'modality': 'TEXT', 'tokenCount': 324}],
    'totalTokenCount': 1681,
    'promptTokenCount': 324},
   'modelVersion': 'gemini-3-flash-preview'},
  'key': 'resume-request-98262'}]

In [243]:
nsm

[{'response': {'candidates': [{'finishReason': 'STOP',
     'index': 0,
     'content': {}}],
   'responseId': 'CBRoab_HOo_O_uMP_9jLyAs',
   'usageMetadata': {'thoughtsTokenCount': 1357,
    'promptTokensDetails': [{'modality': 'TEXT', 'tokenCount': 324}],
    'totalTokenCount': 1681,
    'promptTokenCount': 324},
   'modelVersion': 'gemini-3-flash-preview'},
  'key': 'resume-request-98262'}]