In [38]:
import pandas as pd
import os
import importlib

import modify_cv
import modify_cv2
import load

modify_cv = importlib.reload(modify_cv)
modify_cv2 = importlib.reload(modify_cv2)
load = importlib.reload(load)

ORIGINAL_CVS_FOLDER = "original_cvs"
MODIFIED_CVS_FOLDER = "modified_cvs"

# Load the CVs dataset of UI/UX Designers and Project Managers from `load.ipynb`

In [40]:
uiux_pm_520_df = pd.read_csv(os.path.join(ORIGINAL_CVS_FOLDER, "original_cvs.csv"), index_col=0)

# Load all data and keys

In [41]:
api_keys = load.load_api_keys()

modification_prompt_names, modification_prompts = load.get_modification_prompts()
modification_prompts_dict = dict(zip(modification_prompt_names, modification_prompts))
modification_prompt_from_paper_name = "from_paper"
modification_prompt_from_paper = modification_prompts_dict[modification_prompt_from_paper_name]

job_descriptions_pm_names, job_descriptions_pm = load.get_pm_job_descriptions()
job_descriptions_pm_dict = dict(zip(job_descriptions_pm_names, job_descriptions_pm))
job_description_doordash_name = "doordash_pm"
job_description_doordash = job_descriptions_pm_dict[job_description_doordash_name]

job_descriptions_uiux_names, job_descriptions_uiux = load.get_uiux_job_descriptions()
job_descriptions_uiux_dict = dict(zip(job_descriptions_uiux_names, job_descriptions_uiux))
job_descriptions_google_ux_name = "google_ux"
job_descriptions_google_ux = job_descriptions_uiux_dict[job_descriptions_google_ux_name]

In [46]:
def run_experiment(
    client, df: pd.DataFrame = uiux_pm_520_df, save_to: str | None = None
) -> pd.DataFrame:
    if len(df.columns) == 1:
        df_just_cvs = df[[df.columns[0]]].copy()
    elif "CV" in df.columns:
        df_just_cvs = df[["CV"]].copy()
    else:
        raise ValueError("DataFrame must have either one column or a column named 'CV'")

    df_modified_cvs = client.generate_group_of_cv_s(df_just_cvs)
    if save_to is not None:
        df_modified_cvs.to_csv(save_to)
    return df_modified_cvs

# Modifying CVs with Anthropic's Haiku 4.5

In [47]:
haiku_4_5_modification_client_doordash_original_prompt = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-haiku-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

haiku_4_5_modification_client_google_ux_original_prompt = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-haiku-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [8]:
run_experiment(
    client=haiku_4_5_modification_client_google_ux_original_prompt,
    save_to="uiux_pm_520_haiku_modified_cvs_google_ux.csv",
)

run_experiment(
    client=haiku_4_5_modification_client_doordash_original_prompt,
    save_to="uiux_pm_520_haiku_modified_cvs_doordash.csv",
)

Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_0118jyfJETtLb1KV24NcCg8n is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...
Batch msgbatch_018PLHeb8j3X8jU485fNdrmU is still processing...

      Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5
6018   **Web & UX/UI Designer**\n\n**Professional Sum...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\n- Over ...
6026   # Design Professional\n\n**PROFESSIONAL SUMMAR...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL PROFILE\n\...
15743  # Cloud Architect\n\n**Core Expertise**\nCloud...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

#### And a second modification with the same prompts and model

In [48]:
run_experiment(
    client=haiku_4_5_modification_client_doordash_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "haiku_doordash_pm.csv"), index_col=0),
    save_to="pm_520_haiku_twice_modified_cvs_doordash.csv",
)

Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...
Batch msgbatch_01XzQV7x3kYxeYPHpyJf7w2c is still processing...

      Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5
6018   **Web & UX/UI Designer**\n\n**Professional Sum...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\n- Over ...
6026   # Design Professional\n\n**PROFESSIONAL SUMMAR...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **DEPOSITPHOTOS | Content Researcher**\n\nCrea...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL PROFILE\n\...
15743  # Cloud Architect\n\n**Core Expertise**\nCloud...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

In [49]:
run_experiment(
    client=haiku_4_5_modification_client_google_ux_original_prompt,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "haiku_google_ux.csv"), index_col=0),
    save_to="pm_520_haiku_twice_modified_cvs_google_ux.csv",
)

Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...
Batch msgbatch_016HFbsGN16wLJN7LfzyBSPt is still processing...

      Modified_claude-haiku-4-5_of_Modified_claude-haiku-4-5_of_CV_Modelclaude-haiku-4-5_Modelclaude-haiku-4-5
6018   **WEB AND UX/UI DESIGNER**\n\n**PROFESSIONAL E...
6021   # DESIGN PROFESSIONAL\n\n## PORTFOLIO\nOver 50...
6026   # PROFESSIONAL SUMMARY\n\nDesign Professional ...
9479   # GRAPHIC DESIGNER & UI/UX DESIGNER\n\n## PROF...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\nC...
15743  # Cloud Architect\n\n**Professional Summary**\...
16036  # RESUME\n\n**PROFESSIONAL EXPERIENCE**\n\n**G...
16039  # RESUME\n\n**October 2017 — Present**\n**Team...
16064  # Professional Resume\n\n**E-Commerce Product ...

[520 rows x 1 columns]

# Modify with Anthropic's Opus 4.5

In [50]:
opus_4_5_modification_client_doordash = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-opus-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

opus_4_5_modification_client_google_ux = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-opus-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [14]:
run_experiment(
    opus_4_5_modification_client_doordash,
    uiux_pm_520_df,
    save_to="uiux_pm_520_opus_modified_cvs_doordash.csv",
)

run_experiment(
    opus_4_5_modification_client_google_ux,
    uiux_pm_520_df,
    save_to="uiux_pm_520_opus_modified_cvs_google_ux.csv",
)

Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_01S2ARqLnFuhzNuXwwbj356i is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...
Batch msgbatch_013pRJnqpBHrcCuSmXorMeoB is still processing...

      Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5
6018   # WEB & UX/UI DESIGNER\n\n## Professional Summ...
6021   # PROFESSIONAL EXPERIENCE\n\n**Head of Design ...
6026   **DESIGN PROFESSIONAL**\n\n---\n\nDesign is my...
9479   # GRAPHIC DESIGNER | LEAD GRAPHIC DESIGNER\n\n...
16980  PROFESSIONAL EXPERIENCE\n\nDepositphotos | Con...
...                                                  ...
15679  # DARIA MALININA\n\n**Languages:** Chinese, It...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  **[Name]**\n[Contact Information]\n\n---\n\n**...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

#### And a second modification with the same prompts and model

In [51]:
run_experiment(
    client=opus_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "opus_doordash_pm.csv"), index_col=0),
    save_to="pm_520_opus_twice_modified_cvs_doordash.csv",
)

Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...
Batch msgbatch_019HTtkoRvnZrvuzuWnbqufr is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5_Modelclaude-opus-4-5
6018   # PROFESSIONAL RESUME\n\n## Web Designer & UX/...
6021   # [NAME]\n## Head of Design Department\n\n---\...
6026   # PROFESSIONAL SUMMARY\n\nSenior Product Desig...
9479   # GRAPHIC DESIGNER | UI/UX DESIGNER\n\n## PROF...
16980  **DEPOSITPHOTOS**\n**Content Researcher**\n\n-...
...                                                  ...
15679  # DARIA MALININA\n\n---\n\n## Professional Sum...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # SENIOR MARKETING & BRAND STRATEGY LEADER\n\n...
16039  **Professional Experience**\n\n**Team Lead - E...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

In [52]:
run_experiment(
    client=opus_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "opus_google_ux.csv"), index_col=0),
    save_to="pm_520_opus_twice_modified_cvs_google_ux.csv",
)

Batch msgbatch_01LRKdN2Kj5jd3NUiNm4KJhU is still processing...
Batch msgbatch_01LRKdN2Kj5jd3NUiNm4KJhU is still processing...
Batch msgbatch_01LRKdN2Kj5jd3NUiNm4KJhU is still processing...

      Modified_claude-opus-4-5_of_Modified_claude-opus-4-5_of_CV_Modelclaude-opus-4-5_Modelclaude-opus-4-5
6018   # WEB & UX/UI DESIGNER\n\n## Professional Summ...
6021   # PROFESSIONAL EXPERIENCE\n\n**Head of Design ...
6026   **DESIGN PROFESSIONAL**\n\n---\n\n**SUMMARY**\...
9479   # GRAPHIC DESIGNER | LEAD GRAPHIC DESIGNER\n\n...
16980  PROFESSIONAL EXPERIENCE\n\n**Depositphotos | C...
...                                                  ...
15679  # DARIA MALININA\n\n**Languages:** Chinese, It...
15743  # Cloud Architect\n\n## Professional Summary\n...
16036  # PROFESSIONAL SUMMARY\n\nVersatile marketing ...
16039  **[Name]**\n[Contact Information]\n\n---\n\n**...
16064  # E-COMMERCE & MARKETING PROFESSIONAL\n\n## Su...

[520 rows x 1 columns]

# And with Anthropic's Sonnet 4.5

In [53]:
sonnet_4_5_modification_client_doordash = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-sonnet-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
    prompt_job_desc_filename=job_description_doordash_name,
)

sonnet_4_5_modification_client_google_ux = modify_cv.AnthropicClient(
    input_api_key=api_keys["anthropic"],
    model="claude-sonnet-4-5",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
    prompt_job_desc_filename=job_descriptions_google_ux_name,
)

In [10]:
run_experiment(
    sonnet_4_5_modification_client_doordash,
    uiux_pm_520_df,
    save_to="sonnet_4_5_doordash_original_prompt_modified_cvs.csv",
)

run_experiment(
    sonnet_4_5_modification_client_google_ux,
    uiux_pm_520_df,
    save_to="sonnet_4_5_google_ux_original_prompt_modified_cvs.csv",
)

Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01TbxR3RoxDFyAcERWAGHEpW is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...
Batch msgbatch_01Pk6UmdUcAXJVAqsWoyHc1c is still processing...

      Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Professional Expe...
6021   Over 50 Websites\nMore than 30 Logotypes\n4 Mo...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **Content Researcher**  \nDepositphotos\n\n• R...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\n\...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\n**Team Lead - Email...
16064  **PROFESSIONAL SUMMARY**\n\nResults-driven mar...

[520 rows x 1 columns]

In [54]:
run_experiment(
    client=sonnet_4_5_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "sonnet_doordash_pm.csv"), index_col=0),
    save_to="pm_520_sonnet_twice_modified_cvs_doordash.csv",
)

Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...
Batch msgbatch_01ETbuw5isKvZj858dFsqcCX is still processing...

      Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Professional Expe...
6021   PORTFOLIO HIGHLIGHTS\nOver 50 Websites\nMore t...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  # PROFESSIONAL EXPERIENCE\n\n**Content Researc...
...                                                  ...
15679  # DARIA MALININA\n\n## PROFESSIONAL SUMMARY\n\...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\n**Team Lead - Email...
16064  # PROFESSIONAL SUMMARY\n\nResults-driven marke...

[520 rows x 1 columns]

In [55]:
run_experiment(
    client=sonnet_4_5_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "sonnet_google_ux.csv"), index_col=0),
    save_to="pm_520_sonnet_twice_modified_cvs_google_ux.csv",
)

Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...
Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...
Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...
Batch msgbatch_01TixJfEVXdzjpQCUmtyRNEW is still processing...

      Modified_claude-sonnet-4-5_of_Modified_claude-sonnet-4-5_of_CV_Modelclaude-sonnet-4-5_Modelclaude-sonnet-4-5
6018   # Web & UX/UI Designer\n\n## Skills\n\n- Wiref...
6021   PROFESSIONAL SUMMARY\n\nOver 50 Websites\nMore...
6026   # PROFESSIONAL SUMMARY\n\nDesign professional ...
9479   **GRAPHIC DESIGNER & UI/UX DESIGNER**\n\n**PRO...
16980  **Depositphotos | Content Researcher**\n\nRese...
...                                                  ...
15679  # DARIA MALININA\n\n**Multilingual Professiona...
15743  # PROFESSIONAL SUMMARY\n\nLead Cloud Architect...
16036  # PROFESSIONAL SUMMARY\n\n14+ years of experie...
16039  PROFESSIONAL EXPERIENCE\n\nTeam Lead - Email M...
16064  # Professional Summary\n\nResults-driven e-com...

[520 rows x 1 columns]

# And OpenAI's GPT-5.2

In [15]:
gpt_4_2_modification_client_doordash = modify_cv2.OpenAIClient(
    input_api_key=api_keys["openai"],
    model="gpt-5.2-2025-12-11",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gpt_4_2_modification_client_google_ux = modify_cv2.OpenAIClient(
    input_api_key=api_keys["openai"],
    model="gpt-5.2-2025-12-11",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [35]:
run_experiment(
    gpt_4_2_modification_client_google_ux,
    uiux_pm_520_df,
    save_to="gpt_4_2_google_ux_original_prompt_modified_cvs.csv",
)

run_experiment(
    gpt_4_2_modification_client_doordash,
    uiux_pm_520_df,
    save_to="gpt_4_2_doordash_original_prompt_modified_cvs.csv",
)

Processing 520 CVs in 3 batch(es)
Processing chunk 1/3 (242 CVs)
Batch batch_6967cddc52488190b33c1fc4fd378800 is still validating...

KeyboardInterrupt:

# And Gemini Flash 3 (Preview)

In [ ]:
def start_experiment_gemini(
    client, df: pd.DataFrame = uiux_pm_520_df
) -> str:
    if len(df.columns) == 1:
        df_just_cvs = df[[df.columns[0]]].copy()
    elif "CV" in df.columns:
        df_just_cvs = df[["CV"]].copy()
    else:
        raise ValueError("DataFrame must have either one column or a column named 'CV'")
    batch_id = client.start_batch(df_just_cvs)
    return batch_id


def finish_experiment_gemini(client, batch_id: str, save_to: str, df: pd.DataFrame = uiux_pm_520_df) -> pd.DataFrame:
    if len(df.columns) == 1:
        df_just_cvs = df[[df.columns[0]]].copy()
    elif "CV" in df.columns:
        df_just_cvs = df[["CV"]].copy()
    else:
        raise ValueError("DataFrame must have either one column or a column named 'CV'")
    df_modified_cvs = client.get_batch_results(batch_id, df_just_cvs)
    df_modified_cvs.to_csv(save_to)
    return df_modified_cvs

In [8]:
gemini_flash_3_preview_modification_client_doordash = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-flash-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gemini_flash_3_preview_modification_client_google_ux = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-flash-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [ ]:
flash_3_batch_id_google_ux = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_google_ux,
)

In [29]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_google_ux,
    batch_id=flash_3_batch_id_google_ux,
    save_to="uiux_pm_520_gemini_flash_3_modified_cvs_google_ux.csv",
)

Batch batches/8zfff4num44a3bvrehktp4vxvs0kyfsk246s current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-flash-preview_of_CV_Modelgemini-3-flash-preview
6018   **[NAME]**\n[Phone Number] | [Email Address] |...
6021   **[YOUR NAME]**\n[Your Phone Number] | [Your E...
6026   **[NAME]**\nLead Product Designer | UI/UX & Br...
9479   **[YOUR NAME]**\n[Phone Number] | [Email Addre...
16980  **Depositphotos | Content Researcher**\n\n* Re...
...                                                  ...
15679  DARIA MALININA\n\nPROFESSIONAL SUMMARY\nHighly...
15743  **LEAD CLOUD ARCHITECT**\n\n**Professional Pro...
16036  [NAME]\n[PHONE NUMBER] | [EMAIL] | [LINKEDIN P...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **CHIEF MARKETING OFFICER / RELEASE MANAGER**\...

[520 rows x 1 columns]

In [16]:
flash_3_batch_id_doordash = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_doordash,
)

print("Gemini Flash 3 Batch ID:", flash_3_batch_id_doordash)

Creating batch job for 520 CVs...
Batch job created: batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok
Use get_batch_results('batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok') to retrieve results when complete
Gemini Flash 3 Batch ID: batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok

In [30]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_doordash,
    batch_id=flash_3_batch_id_doordash,
    save_to="uiux_pm_520_gemini_flash_3_modified_cvs_doordash.csv",
)

Batch batches/60sygf6fa0u335xl5kznvahlethnmzz4b9ok current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-flash-preview_of_CV_Modelgemini-3-flash-preview
6018   **Web and UX/UI Designer**\n\n**PROFESSIONAL S...
6021   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
6026   **SENIOR PRODUCT & UI/UX DESIGNER**\n\n**Profe...
9479   [NAME]\n[CONTACT INFORMATION]\n\n**PROFESSIONA...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **LEAD CLOUD ARCHITECT**\n\n**Professional Pro...
16036  **PROFESSIONAL SUMMARY**\n\nAccomplished marke...
16039  **Digital Connect Ukraine**\n**Team Lead - Ema...
16064  **[NAME]**\n**[CONTACT INFORMATION]**\n\n**PRO...

[520 rows x 1 columns]

#### And do it once more with the same model and prompts

In [ ]:
twice_gemini_flash_doordash_batch_id = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_doordash_pm.csv"), index_col=0),
)

print("Gemini Flash 3 Twice Batch ID:", twice_gemini_flash_doordash_batch_id)

twice_gemini_flash_google_ux_batch_id = start_experiment_gemini(
    gemini_flash_3_preview_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_flash_google_ux.csv"), index_col=0),
)

print("Gemini Flash 3 Twice Batch ID:", twice_gemini_flash_google_ux_batch_id)

In [ ]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_doordash,
    batch_id=twice_gemini_flash_doordash_batch_id,
    save_to="pm_520_gemini_flash_twice_modified_cvs_doordash.csv",
)

In [ ]:
finish_experiment_gemini(
    client=gemini_flash_3_preview_modification_client_google_ux,
    batch_id=twice_gemini_flash_google_ux_batch_id,
    save_to="pm_520_gemini_flash_twice_modified_cvs_google_ux.csv",
)

# And Gemini Pro 3 (Preview)

In [18]:

gemini_pro_3_preview_modification_client_doordash = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-pro-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_description_doordash,
)

gemini_pro_3_preview_modification_client_google_ux = modify_cv2.GeminiClient(
    input_api_key=api_keys["google"],
    model="gemini-3-pro-preview",
    prompt_template=modification_prompt_from_paper,
    prompt_template_path=modification_prompt_from_paper_name,
    prompt_job_description=job_descriptions_google_ux,
)

In [19]:

pro_3_batch_id_doordash = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_doordash,
)

print("Gemini Pro 3 Batch ID:", pro_3_batch_id_doordash)

Creating batch job for 520 CVs...
Batch job created: batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6
Use get_batch_results('batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6') to retrieve results when complete
Gemini Pro 3 Batch ID: batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6

In [36]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    batch_id=pro_3_batch_id_doordash,
    save_to="uiux_pm_520_gemini_pro_3_modified_cvs_doordash.csv",
)

Batch batches/2ojsdvcgysuu1n0a2gshral3xyi8jsdtaug6 current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   **PROFESSIONAL SUMMARY**\n\nDedicated Web and ...
6021   **HEAD OF DESIGN**\n\n**PROFESSIONAL SUMMARY**...
6026   **Senior Product & Brand Designer**\n\n**Profe...
9479   [Name]\n[Phone Number] | [Email Address] | [Po...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **Daria Malinina**\n\n**PROFESSIONAL SUMMARY**...
15743  **PROFESSIONAL SUMMARY**\n\nLead Cloud Archite...
16036  **PROFESSIONAL SUMMARY**\n\nSenior Marketing a...
16039  **Team Lead - Email Marketing**\n**Digital Con...
16064  **PROFESSIONAL SUMMARY**\n\nResults-oriented C...

[520 rows x 1 columns]

In [21]:


pro_3_batch_id_google_ux = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_google_ux,
)

print("Gemini Pro 3 Batch ID:", pro_3_batch_id_google_ux)

Creating batch job for 520 CVs...
Batch job created: batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb
Use get_batch_results('batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb') to retrieve results when complete
Gemini Pro 3 Batch ID: batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb

In [37]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    batch_id=pro_3_batch_id_google_ux,
    save_to="uiux_pm_520_gemini_pro_3_modified_cvs_google_ux.csv",
)

Batch batches/z7b448ig0jy54ruzm4un1e6n401gq9i688bb current state: JOB_STATE_SUCCEEDED

      Modified_gemini-3-pro-preview_of_CV_Modelgemini-3-pro-preview
6018   [Name]\n[Phone Number] | [Email Address] | [Po...
6021   **HEAD OF DESIGN DEPARTMENT**\n\n**SUMMARY OF ...
6026   [Your Name]\n[Your Contact Information: Phone ...
9479   **[Your Name]**\n[City, State/Country] | [Phon...
16980  **Depositphotos | Content Researcher**\n\n*   ...
...                                                  ...
15679  **DARIA MALININA**\n\n**PROFESSIONAL SUMMARY**...
15743  **PROFESSIONAL SUMMARY**\n\nLead Cloud Archite...
16036  **PROFESSIONAL SUMMARY**\n\nStrategic Marketin...
16039  **PROFESSIONAL EXPERIENCE**\n\n**Digital Conne...
16064  **PROFESSIONAL SUMMARY**\n\nResults-oriented C...

[520 rows x 1 columns]

#### And a second modification with the same prompts and model

In [ ]:
gemini_pro_doordash_twice_batch_id = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_doordash,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_pro_doordash_pm.csv"), index_col=0),
)

print("Gemini Pro 3 Twice Batch ID:", gemini_pro_doordash_twice_batch_id)

gemini_pro_google_ux_twice_batch_id = start_experiment_gemini(
    gemini_pro_3_preview_modification_client_google_ux,
    df=pd.read_csv(os.path.join(MODIFIED_CVS_FOLDER, "gemini_pro_google_ux.csv"), index_col=0),
)

print("Gemini Pro 3 Twice Batch ID:", gemini_pro_google_ux_twice_batch_id)

In [ ]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_doordash,
    batch_id=gemini_pro_doordash_twice_batch_id,
    save_to="pm_520_gemini_pro_twice_modified_cvs_doordash.csv",
)

In [ ]:
finish_experiment_gemini(
    client=gemini_pro_3_preview_modification_client_google_ux,
    batch_id=gemini_pro_google_ux_twice_batch_id,
    save_to="pm_520_gemini_pro_twice_modified_cvs_google_ux.csv",
)